linters:
  enable-all: true
  disable:
    - scopelint # deprecated
    - interfacer # deprecated
    - maligned # deprecated
    - golint # deprecated
    - deadcode #deprecated
    - nosnakecase #deprecated
    - structcheck #deprecated
    - varcheck #deprecated
    - exhaustivestruct #deprecated
    - ifshort #deprecated
linters-settings:
  varnamelen:
    min-name-length: 1
issues:
  exclude-use-default: false
  exclude-rules:
    - path: _test\.go
      linters:
        - funlen
