before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - format: tar.gz
    format_overrides:
      - goos: windows
        format: zip

release:
  draft: true

changelog:
  sort: asc
  use: github
  groups:
    - title: Features
      regexp: "^.*feat:.*$"
      order: 0
    - title: Bug Fixes
      regexp: "^.*fix:.*$"
      order: 0
    - title: Others
      order: 999
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - Merge pull request
