name: Test
on:
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set Go Version
        run: awk 'NR==3' go.mod | awk '{print "GO_VERSION=" $NF}' >> $GITHUB_ENV

      - name: Setup Go ${{ env.GO_VERSION }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Setup tools
        run: make tools

      - name: Run Test
        run: make check
